# Makefile (BSD make syntax) for eda sources
#
# Copyright 2003-2016 Attila Gy. Molnar
#
# This file is part of eda project.
#
# Eda is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Eda is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Eda.  If not, see <http://www.gnu.org/licenses/>.
#

include ../conf.make
CC = cc

ARCH != uname -m
OS != uname -s
REV != cat ../REV 2>/dev/null || echo 0

CFLAGS = -W -Wall -g -O2 -Wformat -Werror=format-security \
	-Wstack-protector -Wshadow -Wpointer-arith -Wstrict-prototypes -I.. \
	-I/usr/local/include -I/usr/local/include/ncurses

# workaround for ncurses-6.0.0s20171007_1
# /usr/local/lib/libncurses.so.6.0 uses /usr/local/lib/libtinfo.so.6
#LDFLAGS = -L/usr/local/lib -lncurses
LDFLAGS = -L/usr/lib -lncurses

OBJS = main.o ed.o fh.o lll.o cmd.o disp.o keys.o cmdlib.o select.o filter.o \
	util.o search.o tags.o pipe.o rc.o ring.o
SRCS = $(OBJS:.o=.c)

# ------------------------------------

all: eda

eda: $(OBJS)
	$(CC) -o $@ ${.ALLSRC} $(LDFLAGS)

install:
	install -d -m 755  $(DESTDIR)$(prefix)/bin/
	install -m 755 -p -s eda  $(DESTDIR)$(prefix)/bin/
	install -d -m 755 -p  $(DESTDIR)$(sysconfdir)/eda/
	install -m 644 -p edarc edakeys  $(DESTDIR)$(sysconfdir)/eda/
	install -m 644 -p edaseq.$(OS)  $(DESTDIR)$(sysconfdir)/eda/edaseq
	install -d -m 755  $(DESTDIR)$(datadir)/eda/
	install -m 644 -p edarc edakeys edaseq.* edamacro sample.proj  $(DESTDIR)$(datadir)/eda/
	install -m 755 -p xeda set_op.pl  $(DESTDIR)$(datadir)/eda/

uninstall:
	for f in eda ; do \
	  if test -f $(DESTDIR)$(prefix)/bin/$$f ; then rm -f $(DESTDIR)$(prefix)/bin/$$f ; fi ; \
	done
	for f in edarc edakeys edaseq ; do \
	  if test -f $(DESTDIR)$(sysconfdir)/eda/$$f ; then rm -f $(DESTDIR)$(sysconfdir)/eda/$$f ; fi ; \
	done
	-rmdir $(DESTDIR)$(sysconfdir)/eda || true
	for f in edarc edakeys edaseq.* edamacro sample.proj set_op.pl xeda ; do \
	  if test -f $(DESTDIR)$(datadir)/eda/$$f ; then rm -f $(DESTDIR)$(datadir)/eda/$$f ; fi ; \
	done
	-rmdir $(DESTDIR)$(datadir)/eda || true

clean:
	-rm -f *.o *.i *~ eda

# ------------------------------------

main.o: main.c $(SRCS) $(HDRS)
	$(CC) $(CFLAGS) -DREV=\"$(REV)\" -DVERSION=\"$(VERSION)\" -c main.c -o $@

rc.o: rc.c
	$(CC) $(CFLAGS) -DCONFPATH=\"$(sysconfdir)/eda\" -DPROGHOME=\"$(datadir)/eda\" -c rc.c -o $@

keys.o: keys.c
	$(CC) $(CFLAGS) -DCONFPATH=\"$(sysconfdir)/eda\" -c keys.c -o $@

# ------------------------------------

.SUFFIXES: .i .o

#.c.o:
#	$(CC) $(CFLAGS) -o ${.TARGET} -c ${.IMPSRC}
#.c.i:
#	$(CC) -E -W -Wall -I.. -o ${.TARGET} -c ${.IMPSRC}

# ------------------------------------
