/* rkeys.h : generated file, don't edit! */
	{ KN(KEY_RETURN), 0 },
	{ KN(KEY_TAB), 0 },
	{ KN(KEY_ESC), 0 },
	{ KN(KEY_BACKSPACE), 0 },
	{ KN(KEY_ASCII_DEL), 0 },
	{ KN(KEY_IC), 0 },
	{ KN(KEY_DC), 0 },
	{ KN(KEY_HOME), 0 },
	{ KN(KEY_END), 0 },
	{ KN(KEY_UP), 0 },
	{ KN(KEY_DOWN), 0 },
	{ KN(KEY_LEFT), 0 },
	{ KN(KEY_RIGHT), 0 },
	{ KN(KEY_F12), 0 },
	{ KN(KEY_C_C), 0 },
	{ KN(KEY_C_H), 0 },
	{ KN(KEY_C_I), 0 },
	{ KN(KEY_C_M), 0 },
	{ KN(KEY_C_Q), 0 },
	{ KN(KEY_C_S), 0 },
	{ KN(KEY_C_Z), 0 },
#define RESERVED_KEYS 21
