#!/bin/bash
#Usage:
#	xeda [-i initialdir] [eda options] filename [+line] [filename [+line] ...]
#	-i initialdir	change to initialdir before starting eda
#	eda options: 
#	-p project	load project with settings and file list
#	-t 		force tags file load on startup
#	-j symbol	jump to symbol after startup
#	-a macro	macro name to start automatically after startup
#	-n 		no configuration file processing
#
# Copyright 2003-2016 Attila Gy. Molnar
#
# This file is part of eda project.
#
# Eda is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Eda is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Eda.  If not, see <http://www.gnu.org/licenses/>.
#

EDA=`which eda`
[ -x "$EDA" ] || exit 1

#args preprocessing
declare FILENAMES
i=0
OPTIONS=""
PROJECT=""
while [ $# -gt 0 ]; do
	case "$1" in
	-i)
		# initialdir, xeda option
		cd $2 || exit 1
		shift
		;;
	-p)
		PROJECT=$2
		OPTIONS="$OPTIONS -p $2"
		shift
		;;
	-[ja])
		OPTIONS="$OPTIONS $1 $2"
		shift
		;;
	-[tn])
		OPTIONS="$OPTIONS $1"
		;;
	:*|+*)
		FILENAMES[$i]="$1"
		i=$(($i+1))
		;;
	*)
		FILENAMES[$i]="$1"
		i=$(($i+1))
		;;
	esac
	shift
done

# args?
[ ${#FILENAMES[@]} -gt 0 ] || [ "${PROJECT}" ] || FILENAMES[0]="noname"

if [ -z "$DISPLAY" ]; then
	$EDA $OPTIONS "${FILENAMES[@]}"
else
	x-terminal-emulator -e $EDA $OPTIONS "${FILENAMES[@]}"
fi
